### ISSUE TITLE
Create component definition

### ISSUE THREAD

**Issue by KatanaZZZ** [MossbauerLab/UnivemMSAggr#1]
In this task we should create definidion (POCO) of Messbauer sub spectra (singlet, doublet and sextet).

**Comment by KatanaZZZ** [comment]
[Indian (NiFe2)O4-NA-2-4096_comp 10s-2017-3.txt](https://github.com/MossbauerLab/UnivemMSAggr/files/1488039/Indian.NiFe2.O4-NA-2-4096_comp.10s-2017-3.txt)
[Indian (NiFe2)O4-NB-2-4096_comp 10s-2017-3.txt](https://github.com/MossbauerLab/UnivemMSAggr/files/1488040/Indian.NiFe2.O4-NB-2-4096_comp.10s-2017-3.txt)

**Comment by EvilLord666** [comment]
Done
