### ISSUE TITLE
Design issue on windows 10

### ISSUE THREAD

**Issue by Edisson** [MossbauerLab/UnivemMSAggr#8]
Some controls such as buttons on the adding form have an offset down to the bottom to the border of the window. 
It shouldn't looks like that, asymmetrically. Need to be fixed.

**Comment by Edisson** [comment]
I can't run the application on clear Windows 7 (with .net 4.5) yet, 'cos it crashes unreasonably

**Comment by EvilLord666** [comment]
Have not noticed any differences in win 10 from win 7 xaml marup is rigid therefore it is not possible.

![win10_UI](https://user-images.githubusercontent.com/18068522/57192105-82356d00-6f35-11e9-9bee-393920fe0156.png)

**Comment by EvilLord666** [comment]
i don't know how you tried to run app on Win7 with net4.5, but here is an screenshot almost pure system with net 4.5.2 and running UnivemMSAggr:

![univemMsAggrWin7Run](https://user-images.githubusercontent.com/18068522/57192620-e6632b80-6f4b-11e9-9e25-ba6da8a47333.png)
